version: '3.7'
services:
  frontend:
    container_name: spring-petclinic-angular
    build: ./spring-petclinic-angular
    image: cathysimms/spring-petclinic-angular:latest
    depends_on:
    - backend
    networks:
    - my_network
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
  backend:
    environment:
      USER_NAME: ${USER_NAME}
      USER_PASSWORD: ${USER_PASSWORD}
    container_name: spring-petclinic-rest
    build: ./spring-petclinic-rest
    image: cathysimms/spring-petclinic-rest:latest
    networks:
    - my_network
    ports:
    - target: 9966
      published: 9966
      protocol: tcp
  nginx:
    container_name: nginx
    image: nginx:latest
    networks:
    - my_network
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
    - backend

networks:
  my_network: